import { PropertyProps } from "@/interfaces";
import img1 from "../public/images/Leonardo_Phoenix_Nestled_atop_a_rolling_hill_on_the_edge_of_to_0.jpg";
import img2 from "../public/images/image 2.png";
import img3 from "../public/images/Leonardo_Phoenix_Nestled_atop_a_rolling_hill_on_the_edge_of_to_2.jpg";
import img4 from "../public/images/Leonardo_Phoenix_Nestled_atop_a_rolling_hill_on_the_edge_of_to_3.jpg";
import img5 from "../public/images/pexels-asphotograpy-101808.jpg";
import img6 from "../public/images/pexels-asphotograpy-565324.jpg";
import img7 from "../public/images/pexels-expect-best-79873-323780.jpg";
import img8 from "../public/images/pexels-frans-van-heerden-201846-1438832.jpg";
import img9 from "../public/images/pexels-frans-van-heerden-201846-1438834.jpg";
import img10 from "../public/images/pexels-godless-humanist-739743-1587947.jpg";
import img11 from "../public/images/pexels-marketingtuig-87223.jpg";
import img12 from "../public/images/pexels-nextvoyage-1481105.jpg";
import img13 from "../public/images/pexels-pixabay-209296.jpg";

export const PROPERTYLISTINGSAMPLE: PropertyProps[] = [
  {
    id: 1,
    name: "Villa Ocean Breeze",
    address: {
      state: "Greater Accra Region",
      city: "Accra",
      country: "Ghana",
    },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    price: 3200,
    agentFeePercentage: 5,
    walkingFee: 50,
    acceptableDurations: [1, 2, 3],
    beds: 3,
    image: img1.src,
    images: [img1.src, img2.src, img3.src, img4.src],
    discount: "",
    description:
      "Experience the ultimate beachfront luxury at Villa Ocean Breeze. This stunning villa offers breathtaking ocean views, a private pool, and modern amenities to ensure a comfortable and memorable stay.",
    amenities: ["Free WiFi", "Pool", "Air Conditioning", "Kitchen"],
    reviews: [
      { user: "Hawawu", comment: "Great place!", rating: 5 },
      { user: "Maltiti", comment: "Very clean and cozy", rating: 4 },
    ],
  },
  {
    id: 2,
    name: "Mountain Escape Chalet",
    address: {
      state: "Ashanti Region",
      city: "Kumasi",
      country: "Ghana",
    },
    rating: 4.7,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    price: 1800,
    agentFeePercentage: 10,
    walkingFee: 150,
    acceptableDurations: [1],
    beds: 4,
    image: img2.src,
    images: [img2.src, img1.src, img5.src],
    discount: "30",
    description:
      "Escape into the serene mountains with this rustic yet modern chalet. Ideal for family trips, it offers a cozy fireplace and breathtaking views of the surrounding peaks.",
    amenities: ["Fireplace", "Free WiFi", "Heating", "Balcony", "Kitchen"],
    reviews: [
      {
        user: "Issahaku",
        comment: "The view from the balcony was unforgettable.",
        rating: 5,
      },
      {
        user: "Suleman",
        comment: "Warm and cozy, loved the fireplace!",
        rating: 4.5,
      },
    ],
  },
  {
    id: 3,
    name: "Cozy Desert Retreat",
    address: {
      state: "Northern Region",
      city: "Tamale",
      country: "Ghana",
    },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    price: 1500,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3, 4],
    beds: 2,
    image: img3.src,
    images: [img3.src, img6.src, img7.src],
    discount: "",
    description:
      "This desert retreat is perfect for those seeking peace and quiet. Watch the sunset over the desert landscape and enjoy a night under the stars.",
    amenities: [
      "Air Conditioning",
      "Free Parking",
      "Outdoor Lounge",
      "Kitchen",
    ],
    reviews: [
      {
        user: "Abdulai",
        comment: "Very peaceful, I slept so well.",
        rating: 5,
      },
      {
        user: "Maltiti",
        comment: "Loved watching the stars at night.",
        rating: 4.8,
      },
    ],
  },
  {
    id: 4,
    name: "City Lights Penthouse",
    address: {
      state: "Greater Accra Region",
      city: "Tema",
      country: "Ghana",
    },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    price: 4500,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 2,
    image: img4.src,
    images: [img4.src, img8.src, img9.src, img10.src],
    discount: "15",
    description:
      "A luxurious penthouse in the heart of the city. Floor-to-ceiling windows give you panoramic views of the skyline and a modern living space.",
    amenities: ["High-speed WiFi", "24h Concierge", "Rooftop Access", "Gym"],
    reviews: [
      {
        user: "Yakubu",
        comment: "The city view is priceless.",
        rating: 5,
      },
      { user: "Hawawu", comment: "Stylish and very clean.", rating: 4.7 },
    ],
  },
  {
    id: 5,
    name: "Riverside Cabin",
    address: {
      state: "Eastern Region",
      city: "Koforidua",
      country: "Ghana",
    },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    price: 2800,
    agentFeePercentage: 0,
    walkingFee: 100,
    acceptableDurations: [1, 2, 3],
    beds: 3,
    image: img5.src,
    images: [img5.src, img11.src, img12.src],
    discount: "20",
    description:
      "Relax by the riverside in this peaceful cabin. Guests can enjoy the serene environment or have a quiet evening by the water.",
    amenities: ["Private Dock", "Fireplace", "Outdoor Grill"],
    reviews: [
      {
        user: "Fuseini",
        comment: "The riverside location was amazing.",
        rating: 4.9,
      },
      { user: "Mariam", comment: "So calm and refreshing.", rating: 4.6 },
    ],
  },
  {
    id: 6,
    name: "Modern Beachfront Villa",
    address: {
      state: "Central Region",
      city: "Cape Coast",
      country: "Ghana",
    },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 5000,
    agentFeePercentage: 0,
    walkingFee: 0,
    acceptableDurations: [1, 2, 3],
    beds: 5,
    image: img6.src,
    images: [img6.src, img13.src, img1.src, img2.src],
    discount: "",
    description:
      "Luxury meets relaxation in this beachfront villa with a private pool. Guests enjoy excellent service and direct beach access.",
    amenities: ["Infinity Pool", "Beach Access", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "Best vacation of my life.", rating: 5 },
      {
        user: "Rahama",
        comment: "The service was wonderful!",
        rating: 4.8,
      },
    ],
  },
  {
    id: 7,
    name: "Lakeside Chalet",
    address: {
      state: "Volta Region",
      city: "Ho",
      country: "Ghana",
    },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    price: 2300,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 3,
    image: img7.src,
    images: [img7.src, img3.src],
    discount: "10",
    description:
      "Enjoy the beautiful lake views from this comfortable chalet with access to hiking trails.",
    amenities: ["Lake Access", "Hiking Trails", "Fireplace", "Kitchen"],
  },
  {
    id: 8,
    name: "Tropical Garden Villa",
    address: {
      state: "Greater Accra Region",
      city: "Accra",
      country: "Ghana",
    },
    rating: 4.8,
    category: ["Garden", "Free Parking", "Self Checkin"],
    price: 2750,
    agentFeePercentage: 15,
    walkingFee: 0,
    acceptableDurations: [1, 2, 3],
    beds: 3,
    image: img8.src,
    images: [img8.src, img4.src, img5.src],
    discount: "25",
    description:
      "A beautiful villa surrounded by tropical gardens, offering privacy and comfort.",
  },
  {
    id: 9,
    name: "Urban Loft",
    address: {
      state: "Ashanti Region",
      city: "Kumasi",
      country: "Ghana",
    },
    rating: 4.6,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    price: 2000,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 2,
    image: img9.src,
    images: [img9.src, img6.src],
    discount: "",
    description:
      "Modern urban living in the heart of the city with all amenities within reach.",
    amenities: ["Free WiFi", "City Center Location", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "Great city experience.", rating: 5 },
      {
        user: "Bindawdi",
        comment: "Perfect location!",
        rating: 4.8,
      },
    ],
  },
  {
    id: 10,
    name: "Secluded Forest Cabin",
    address: {
      state: "Western Region",
      city: "Takoradi",
      country: "Ghana",
    },
    rating: 4.72,
    category: ["Secluded", "Hot Tub", "Self Checkin"],
    price: 2600,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 4,
    image: img10.src,
    images: [img10.src, img7.src, img8.src],
    discount: "40",
    description:
      "A secluded cabin nestled in the forest, perfect for those seeking tranquility and nature.",
    amenities: ["Hot Tub", "Forest View", "Fireplace", "Kitchen"],
    reviews: [
      { user: "Alhassan", comment: "So peaceful and quiet.", rating: 5 },
      {
        user: "Hayate",
        comment: "Loved the forest surroundings!",
        rating: 4.8,
      },
    ],
  },
  {
    id: 11,
    name: "Cliffside Villa",
    address: {
      state: "Central Region",
      city: "Elmina",
      country: "Ghana",
    },
    rating: 4.93,
    category: ["Cliffside", "Infinity Pool", "Sea View"],
    price: 6000,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 4,
    image: img11.src,
    images: [img11.src, img9.src, img10.src, img12.src],
    discount: "50",
    description:
      "Stunning cliffside villa with infinity pool and breathtaking sea views.",
    amenities: ["Infinity Pool", "Sea View", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "The views were incredible.", rating: 5 },
      {
        user: "Rahama",
        comment: "Perfect for a luxury getaway!",
        rating: 4.8,
      },
    ],
  },
  {
    id: 12,
    name: "Coastal Escape Villa",
    address: {
      state: "Western Region",
      city: "Axim",
      country: "Ghana",
    },
    rating: 4.83,
    category: ["Beachfront", "Pet Friendly", "Free Parking"],
    price: 3400,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 3,
    image: img12.src,
    images: [img12.src, img13.src, img1.src],
    discount: "",
    description:
      "Beautiful coastal villa with direct beach access and pet-friendly amenities.",
    amenities: ["Beach Access", "Pet Friendly", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "Our dogs loved it!", rating: 5 },
      {
        user: "Rahama",
        comment: "Perfect beach vacation.",
        rating: 4.8,
      },
    ],
  },
  {
    id: 13,
    name: "Historical Villa",
    address: {
      state: "Greater Accra Region",
      city: "Jamestown",
      country: "Ghana",
    },
    rating: 4.67,
    category: ["Historical", "Free Breakfast", "Self Checkin"],
    price: 2700,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 2,
    image: img13.src,
    images: [img13.src, img2.src, img3.src],
    discount: "35",
    description:
      "Experience Ghana's rich history in this beautifully preserved historical villa.",
    amenities: ["Historical Building", "Free Breakfast", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "Fascinating history!", rating: 5 },
      {
        user: "Rahama",
        comment: "Beautiful architecture.",
        rating: 4.8,
      },
    ],
  },
  {
    id: 14,
    name: "Downtown Apartment",
    address: {
      state: "Greater Accra Region",
      city: "Accra",
      country: "Ghana",
    },
    rating: 4.81,
    category: ["City Center", "Free WiFi", "Public Transport"],
    price: 2200,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 1,
    image: img1.src,
    images: [img1.src, img4.src],
    discount: "",
    description:
      "Convenient downtown apartment with easy access to public transport and city amenities.",
    amenities: ["City Center", "Public Transport Access", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "Great location!", rating: 5 },
      {
        user: "Rahama",
        comment: "Very convenient for exploring the city.",
        rating: 4.8,
      },
    ],
  },
  {
    id: 15,
    name: "Luxury Safari Lodge",
    address: {
      state: "Northern Region",
      city: "Mole",
      country: "Ghana",
    },
    rating: 4.97,
    category: ["Safari", "Guided Tours", "Free Breakfast"],
    price: 4500,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 4,
    image: img2.src,
    images: [img2.src, img5.src, img6.src, img7.src],
    discount: "20",
    description:
      "Luxury lodge experience with guided safari tours in Ghana's beautiful national park.",
    amenities: ["Guided Tours", "Free Breakfast", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "Amazing wildlife experience.", rating: 5 },
      {
        user: "Rahama",
        comment: "The guides were very knowledgeable!",
        rating: 4.8,
      },
    ],
  },
  {
    id: 16,
    name: "Countryside Cottage",
    address: {
      state: "Eastern Region",
      city: "Aburi",
      country: "Ghana",
    },
    rating: 4.58,
    category: ["Countryside", "Fireplace", "Self Checkin"],
    price: 1800,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 2,
    image: img3.src,
    images: [img3.src, img8.src],
    discount: "25",
    description:
      "Charming countryside cottage surrounded by nature, perfect for a peaceful retreat.",
    amenities: ["Countryside Location", "Fireplace", "Kitchen"],
    reviews: [
      { user: "Alhassan", comment: "So peaceful and quiet.", rating: 5 },
      {
        user: "Rahama",
        comment: "Perfect countryside escape.",
        rating: 4.8,
      },
    ],
  },
  {
    id: 17,
    name: "Riverfront Mansion",
    address: {
      state: "Volta Region",
      city: "Ada",
      country: "Ghana",
    },
    rating: 4.86,
    category: ["Riverfront", "Private Garden", "Self Checkin"],
    price: 5000,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 4,
    image: img4.src,
    images: [img4.src, img9.src, img10.src, img11.src],
    discount: "30",
    description:
      "Magnificent riverfront mansion with private garden and stunning water views.",
    amenities: ["Riverfront", "Private Garden", "Air Conditioning"],
    reviews: [
      {
        user: "Alhassan",
        comment: "The river views were spectacular.",
        rating: 5,
      },
      {
        user: "Rahama",
        comment: "Such a luxurious property!",
        rating: 4.8,
      },
    ],
  },
  {
    id: 18,
    name: "Mountain View Chalet",
    address: {
      state: "Eastern Region",
      city: "Mpraeso",
      country: "Ghana",
    },
    rating: 4.75,
    category: ["Mountain View", "Hiking Access", "Fireplace"],
    price: 3900,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2],
    beds: 3,
    image: img5.src,
    images: [img5.src, img12.src, img13.src],
    discount: "",
    description:
      "Beautiful chalet with stunning mountain views and access to hiking trails.",
    amenities: ["Mountain View", "Hiking Access", "Fireplace", "Kitchen"],
  },
  {
    id: 19,
    name: "Island Paradise Villa",
    address: {
      state: "Greater Accra Region",
      city: "Kokrobite",
      country: "Ghana",
    },
    rating: 4.98,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 6500,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 5,
    image: img6.src,
    images: [img6.src, img1.src, img2.src, img3.src],
    discount: "60",
    description:
      "Luxury island-style villa with private pool and excellent service near the beach.",
    amenities: ["Private Pool", "Beach Access", "Air Conditioning"],
    reviews: [
      { user: "Alhassan", comment: "True paradise!", rating: 5 },
      {
        user: "Rahama",
        comment: "The pool was amazing!",
        rating: 4.8,
      },
    ],
  },
  {
    id: 20,
    name: "Clifftop Retreat",
    address: {
      state: "Central Region",
      city: "Cape Coast",
      country: "Ghana",
    },
    rating: 4.78,
    category: ["Ocean View", "Private Pool", "Self Checkin"],
    price: 4100,
    agentFeePercentage: 6,
    walkingFee: 30,
    acceptableDurations: [1, 2, 3],
    beds: 3,
    image: img7.src,
    images: [img7.src, img4.src, img5.src],
    discount: "",
    description:
      "Breathtaking clifftop retreat with private pool and panoramic ocean views.",
    amenities: ["Private Pool", "Ocean View", "Air Conditioning"],
    reviews: [
      {
        user: "Alhassan",
        comment: "The ocean views were stunning.",
        rating: 5,
      },
      {
        user: "Rahama",
        comment: "Perfect romantic getaway!",
        rating: 4.8,
      },
    ],
  },
];
